; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=aggressive-instcombine -mtriple=x86_64-- -mattr=+avx2 -data-layout="e-n64" -S %s | FileCheck %s --check-prefix=LE
; RUN: opt -passes=aggressive-instcombine -mtriple=x86_64-- -mattr=+avx2 -data-layout="E-n64" -S %s | FileCheck %s --check-prefix=BE

declare void @llvm.assume(i1)

define i64 @pack4_i8_le_shift_var_step(ptr %p, i64 %acc, i64 %s, i64 %step) {
; LE-LABEL: define i64 @pack4_i8_le_shift_var_step(
; LE-SAME: ptr [[P:%.*]], i64 [[ACC:%.*]], i64 [[S:%.*]], i64 [[STEP:%.*]]) #[[ATTR1:[0-9]+]] {
; LE-NEXT:    [[STEP_IS_8:%.*]] = icmp eq i64 [[STEP]], 8
; LE-NEXT:    call void @llvm.assume(i1 [[STEP_IS_8]])
; LE-NEXT:    [[LO:%.*]] = icmp uge i64 [[S]], 24
; LE-NEXT:    call void @llvm.assume(i1 [[LO]])
; LE-NEXT:    [[HI:%.*]] = icmp ult i64 [[S]], 64
; LE-NEXT:    call void @llvm.assume(i1 [[HI]])
; LE-NEXT:    [[STEP2:%.*]] = shl i64 [[STEP]], 1
; LE-NEXT:    [[STEP3:%.*]] = add i64 [[STEP2]], [[STEP]]
; LE-NEXT:    [[S0:%.*]] = sub nsw i64 [[S]], [[STEP3]]
; LE-NEXT:    [[B0:%.*]] = load i32, ptr [[P]], align 1
; LE-NEXT:    [[Z0:%.*]] = zext i32 [[B0]] to i64
; LE-NEXT:    [[SH0:%.*]] = shl i64 [[Z0]], [[S0]]
; LE-NEXT:    [[OR0:%.*]] = or i64 [[ACC]], [[SH0]]
; LE-NEXT:    ret i64 [[OR0]]
;
; BE-LABEL: define i64 @pack4_i8_le_shift_var_step(
; BE-SAME: ptr [[P:%.*]], i64 [[ACC:%.*]], i64 [[S:%.*]], i64 [[STEP:%.*]]) #[[ATTR1:[0-9]+]] {
; BE-NEXT:    [[STEP_IS_8:%.*]] = icmp eq i64 [[STEP]], 8
; BE-NEXT:    call void @llvm.assume(i1 [[STEP_IS_8]])
; BE-NEXT:    [[LO:%.*]] = icmp uge i64 [[S]], 24
; BE-NEXT:    call void @llvm.assume(i1 [[LO]])
; BE-NEXT:    [[HI:%.*]] = icmp ult i64 [[S]], 64
; BE-NEXT:    call void @llvm.assume(i1 [[HI]])
; BE-NEXT:    [[STEP2:%.*]] = shl i64 [[STEP]], 1
; BE-NEXT:    [[STEP3:%.*]] = add i64 [[STEP2]], [[STEP]]
; BE-NEXT:    [[S0:%.*]] = sub nsw i64 [[S]], [[STEP3]]
; BE-NEXT:    [[B0:%.*]] = load i8, ptr [[P]], align 1
; BE-NEXT:    [[Z0:%.*]] = zext i8 [[B0]] to i64
; BE-NEXT:    [[SH0:%.*]] = shl i64 [[Z0]], [[S0]]
; BE-NEXT:    [[OR0:%.*]] = or i64 [[ACC]], [[SH0]]
; BE-NEXT:    [[P1:%.*]] = getelementptr i8, ptr [[P]], i64 1
; BE-NEXT:    [[S1:%.*]] = sub nsw i64 [[S]], [[STEP2]]
; BE-NEXT:    [[B1:%.*]] = load i8, ptr [[P1]], align 1
; BE-NEXT:    [[Z1:%.*]] = zext i8 [[B1]] to i64
; BE-NEXT:    [[SH1:%.*]] = shl i64 [[Z1]], [[S1]]
; BE-NEXT:    [[OR1:%.*]] = or i64 [[OR0]], [[SH1]]
; BE-NEXT:    [[P2:%.*]] = getelementptr i8, ptr [[P]], i64 2
; BE-NEXT:    [[S2:%.*]] = sub nsw i64 [[S]], [[STEP]]
; BE-NEXT:    [[B2:%.*]] = load i8, ptr [[P2]], align 1
; BE-NEXT:    [[Z2:%.*]] = zext i8 [[B2]] to i64
; BE-NEXT:    [[SH2:%.*]] = shl i64 [[Z2]], [[S2]]
; BE-NEXT:    [[OR2:%.*]] = or i64 [[OR1]], [[SH2]]
; BE-NEXT:    [[P3:%.*]] = getelementptr i8, ptr [[P]], i64 3
; BE-NEXT:    [[B3:%.*]] = load i8, ptr [[P3]], align 1
; BE-NEXT:    [[Z3:%.*]] = zext i8 [[B3]] to i64
; BE-NEXT:    [[SH3:%.*]] = shl i64 [[Z3]], [[S]]
; BE-NEXT:    [[R:%.*]] = or i64 [[OR2]], [[SH3]]
; BE-NEXT:    ret i64 [[R]]
;
  %step.is.8 = icmp eq i64 %step, 8
  call void @llvm.assume(i1 %step.is.8)

  %lo = icmp uge i64 %s, 24
  call void @llvm.assume(i1 %lo)
  %hi = icmp ult i64 %s, 64
  call void @llvm.assume(i1 %hi)

  %step2 = shl i64 %step, 1
  %step3 = add i64 %step2, %step

  %s0 = sub nsw i64 %s, %step3
  %b0 = load i8, ptr %p, align 1
  %z0 = zext i8 %b0 to i64
  %sh0 = shl i64 %z0, %s0
  %or0 = or i64 %acc, %sh0

  %p1 = getelementptr i8, ptr %p, i64 1
  %s1 = sub nsw i64 %s, %step2
  %b1 = load i8, ptr %p1, align 1
  %z1 = zext i8 %b1 to i64
  %sh1 = shl i64 %z1, %s1
  %or1 = or i64 %or0, %sh1

  %p2 = getelementptr i8, ptr %p, i64 2
  %s2 = sub nsw i64 %s, %step
  %b2 = load i8, ptr %p2, align 1
  %z2 = zext i8 %b2 to i64
  %sh2 = shl i64 %z2, %s2
  %or2 = or i64 %or1, %sh2

  %p3 = getelementptr i8, ptr %p, i64 3
  %b3 = load i8, ptr %p3, align 1
  %z3 = zext i8 %b3 to i64
  %sh3 = shl i64 %z3, %s
  %r = or i64 %or2, %sh3

  ret i64 %r
}

define i64 @no_fold_without_shift_range(ptr %p, i64 %acc, i64 %s) {
; LE-LABEL: define i64 @no_fold_without_shift_range(
; LE-SAME: ptr [[P:%.*]], i64 [[ACC:%.*]], i64 [[S:%.*]]) #[[ATTR1]] {
; LE-NEXT:    [[S0:%.*]] = sub i64 [[S]], 24
; LE-NEXT:    [[B0:%.*]] = load i8, ptr [[P]], align 1
; LE-NEXT:    [[Z0:%.*]] = zext i8 [[B0]] to i64
; LE-NEXT:    [[SH0:%.*]] = shl i64 [[Z0]], [[S0]]
; LE-NEXT:    [[P1:%.*]] = getelementptr i8, ptr [[P]], i64 1
; LE-NEXT:    [[S1:%.*]] = sub i64 [[S]], 16
; LE-NEXT:    [[B1:%.*]] = load i8, ptr [[P1]], align 1
; LE-NEXT:    [[Z1:%.*]] = zext i8 [[B1]] to i64
; LE-NEXT:    [[SH1:%.*]] = shl i64 [[Z1]], [[S1]]
; LE-NEXT:    [[P2:%.*]] = getelementptr i8, ptr [[P]], i64 2
; LE-NEXT:    [[S2:%.*]] = sub i64 [[S]], 8
; LE-NEXT:    [[B2:%.*]] = load i8, ptr [[P2]], align 1
; LE-NEXT:    [[Z2:%.*]] = zext i8 [[B2]] to i64
; LE-NEXT:    [[SH2:%.*]] = shl i64 [[Z2]], [[S2]]
; LE-NEXT:    [[P3:%.*]] = getelementptr i8, ptr [[P]], i64 3
; LE-NEXT:    [[B3:%.*]] = load i8, ptr [[P3]], align 1
; LE-NEXT:    [[Z3:%.*]] = zext i8 [[B3]] to i64
; LE-NEXT:    [[SH3:%.*]] = shl i64 [[Z3]], [[S]]
; LE-NEXT:    [[OR0:%.*]] = or i64 [[ACC]], [[SH0]]
; LE-NEXT:    [[OR1:%.*]] = or i64 [[OR0]], [[SH1]]
; LE-NEXT:    [[OR2:%.*]] = or i64 [[OR1]], [[SH2]]
; LE-NEXT:    [[R:%.*]] = or i64 [[OR2]], [[SH3]]
; LE-NEXT:    ret i64 [[R]]
;
; BE-LABEL: define i64 @no_fold_without_shift_range(
; BE-SAME: ptr [[P:%.*]], i64 [[ACC:%.*]], i64 [[S:%.*]]) #[[ATTR1]] {
; BE-NEXT:    [[S0:%.*]] = sub i64 [[S]], 24
; BE-NEXT:    [[B0:%.*]] = load i8, ptr [[P]], align 1
; BE-NEXT:    [[Z0:%.*]] = zext i8 [[B0]] to i64
; BE-NEXT:    [[SH0:%.*]] = shl i64 [[Z0]], [[S0]]
; BE-NEXT:    [[P1:%.*]] = getelementptr i8, ptr [[P]], i64 1
; BE-NEXT:    [[S1:%.*]] = sub i64 [[S]], 16
; BE-NEXT:    [[B1:%.*]] = load i8, ptr [[P1]], align 1
; BE-NEXT:    [[Z1:%.*]] = zext i8 [[B1]] to i64
; BE-NEXT:    [[SH1:%.*]] = shl i64 [[Z1]], [[S1]]
; BE-NEXT:    [[P2:%.*]] = getelementptr i8, ptr [[P]], i64 2
; BE-NEXT:    [[S2:%.*]] = sub i64 [[S]], 8
; BE-NEXT:    [[B2:%.*]] = load i8, ptr [[P2]], align 1
; BE-NEXT:    [[Z2:%.*]] = zext i8 [[B2]] to i64
; BE-NEXT:    [[SH2:%.*]] = shl i64 [[Z2]], [[S2]]
; BE-NEXT:    [[P3:%.*]] = getelementptr i8, ptr [[P]], i64 3
; BE-NEXT:    [[B3:%.*]] = load i8, ptr [[P3]], align 1
; BE-NEXT:    [[Z3:%.*]] = zext i8 [[B3]] to i64
; BE-NEXT:    [[SH3:%.*]] = shl i64 [[Z3]], [[S]]
; BE-NEXT:    [[OR0:%.*]] = or i64 [[ACC]], [[SH0]]
; BE-NEXT:    [[OR1:%.*]] = or i64 [[OR0]], [[SH1]]
; BE-NEXT:    [[OR2:%.*]] = or i64 [[OR1]], [[SH2]]
; BE-NEXT:    [[R:%.*]] = or i64 [[OR2]], [[SH3]]
; BE-NEXT:    ret i64 [[R]]
;
  %s0 = sub i64 %s, 24
  %b0 = load i8, ptr %p, align 1
  %z0 = zext i8 %b0 to i64
  %sh0 = shl i64 %z0, %s0

  %p1 = getelementptr i8, ptr %p, i64 1
  %s1 = sub i64 %s, 16
  %b1 = load i8, ptr %p1, align 1
  %z1 = zext i8 %b1 to i64
  %sh1 = shl i64 %z1, %s1

  %p2 = getelementptr i8, ptr %p, i64 2
  %s2 = sub i64 %s, 8
  %b2 = load i8, ptr %p2, align 1
  %z2 = zext i8 %b2 to i64
  %sh2 = shl i64 %z2, %s2

  %p3 = getelementptr i8, ptr %p, i64 3
  %b3 = load i8, ptr %p3, align 1
  %z3 = zext i8 %b3 to i64
  %sh3 = shl i64 %z3, %s

  %or0 = or i64 %acc, %sh0
  %or1 = or i64 %or0, %sh1
  %or2 = or i64 %or1, %sh2
  %r = or i64 %or2, %sh3
  ret i64 %r
}

define i64 @no_fold_across_clobber(ptr %p, ptr %q, i64 %acc, i64 %s) {
; LE-LABEL: define i64 @no_fold_across_clobber(
; LE-SAME: ptr [[P:%.*]], ptr [[Q:%.*]], i64 [[ACC:%.*]], i64 [[S:%.*]]) #[[ATTR1]] {
; LE-NEXT:    [[LO:%.*]] = icmp uge i64 [[S]], 24
; LE-NEXT:    call void @llvm.assume(i1 [[LO]])
; LE-NEXT:    [[HI:%.*]] = icmp ult i64 [[S]], 64
; LE-NEXT:    call void @llvm.assume(i1 [[HI]])
; LE-NEXT:    [[S0:%.*]] = sub i64 [[S]], 24
; LE-NEXT:    [[B0:%.*]] = load i16, ptr [[P]], align 1
; LE-NEXT:    store i8 0, ptr [[Q]], align 1
; LE-NEXT:    [[P2:%.*]] = getelementptr i8, ptr [[P]], i64 2
; LE-NEXT:    [[S2:%.*]] = sub i64 [[S]], 8
; LE-NEXT:    [[B2:%.*]] = load i8, ptr [[P2]], align 1
; LE-NEXT:    [[Z2:%.*]] = zext i8 [[B2]] to i64
; LE-NEXT:    [[SH2:%.*]] = shl i64 [[Z2]], [[S2]]
; LE-NEXT:    [[P3:%.*]] = getelementptr i8, ptr [[P]], i64 3
; LE-NEXT:    [[B3:%.*]] = load i8, ptr [[P3]], align 1
; LE-NEXT:    [[Z3:%.*]] = zext i8 [[B3]] to i64
; LE-NEXT:    [[SH3:%.*]] = shl i64 [[Z3]], [[S]]
; LE-NEXT:    [[TMP1:%.*]] = zext i16 [[B0]] to i64
; LE-NEXT:    [[TMP3:%.*]] = shl i64 [[TMP1]], [[S0]]
; LE-NEXT:    [[TMP4:%.*]] = or i64 [[ACC]], [[TMP3]]
; LE-NEXT:    [[OR2:%.*]] = or i64 [[TMP4]], [[SH2]]
; LE-NEXT:    [[R:%.*]] = or i64 [[OR2]], [[SH3]]
; LE-NEXT:    ret i64 [[R]]
;
; BE-LABEL: define i64 @no_fold_across_clobber(
; BE-SAME: ptr [[P:%.*]], ptr [[Q:%.*]], i64 [[ACC:%.*]], i64 [[S:%.*]]) #[[ATTR1]] {
; BE-NEXT:    [[LO:%.*]] = icmp uge i64 [[S]], 24
; BE-NEXT:    call void @llvm.assume(i1 [[LO]])
; BE-NEXT:    [[HI:%.*]] = icmp ult i64 [[S]], 64
; BE-NEXT:    call void @llvm.assume(i1 [[HI]])
; BE-NEXT:    [[S0:%.*]] = sub i64 [[S]], 24
; BE-NEXT:    [[B0:%.*]] = load i8, ptr [[P]], align 1
; BE-NEXT:    [[Z0:%.*]] = zext i8 [[B0]] to i64
; BE-NEXT:    [[TMP2:%.*]] = shl i64 [[Z0]], [[S0]]
; BE-NEXT:    [[P1:%.*]] = getelementptr i8, ptr [[P]], i64 1
; BE-NEXT:    [[S1:%.*]] = sub i64 [[S]], 16
; BE-NEXT:    [[B1:%.*]] = load i8, ptr [[P1]], align 1
; BE-NEXT:    [[Z1:%.*]] = zext i8 [[B1]] to i64
; BE-NEXT:    [[SH1:%.*]] = shl i64 [[Z1]], [[S1]]
; BE-NEXT:    store i8 0, ptr [[Q]], align 1
; BE-NEXT:    [[P2:%.*]] = getelementptr i8, ptr [[P]], i64 2
; BE-NEXT:    [[S2:%.*]] = sub i64 [[S]], 8
; BE-NEXT:    [[B2:%.*]] = load i8, ptr [[P2]], align 1
; BE-NEXT:    [[Z2:%.*]] = zext i8 [[B2]] to i64
; BE-NEXT:    [[SH2:%.*]] = shl i64 [[Z2]], [[S2]]
; BE-NEXT:    [[P3:%.*]] = getelementptr i8, ptr [[P]], i64 3
; BE-NEXT:    [[B3:%.*]] = load i8, ptr [[P3]], align 1
; BE-NEXT:    [[Z3:%.*]] = zext i8 [[B3]] to i64
; BE-NEXT:    [[SH3:%.*]] = shl i64 [[Z3]], [[S]]
; BE-NEXT:    [[TMP3:%.*]] = or i64 [[ACC]], [[TMP2]]
; BE-NEXT:    [[OR1:%.*]] = or i64 [[TMP3]], [[SH1]]
; BE-NEXT:    [[OR2:%.*]] = or i64 [[OR1]], [[SH2]]
; BE-NEXT:    [[R:%.*]] = or i64 [[OR2]], [[SH3]]
; BE-NEXT:    ret i64 [[R]]
;
  %lo = icmp uge i64 %s, 24
  call void @llvm.assume(i1 %lo)
  %hi = icmp ult i64 %s, 64
  call void @llvm.assume(i1 %hi)

  %s0 = sub i64 %s, 24
  %b0 = load i8, ptr %p, align 1
  %z0 = zext i8 %b0 to i64
  %sh0 = shl i64 %z0, %s0

  %p1 = getelementptr i8, ptr %p, i64 1
  %s1 = sub i64 %s, 16
  %b1 = load i8, ptr %p1, align 1
  %z1 = zext i8 %b1 to i64
  %sh1 = shl i64 %z1, %s1

  store i8 0, ptr %q, align 1

  %p2 = getelementptr i8, ptr %p, i64 2
  %s2 = sub i64 %s, 8
  %b2 = load i8, ptr %p2, align 1
  %z2 = zext i8 %b2 to i64
  %sh2 = shl i64 %z2, %s2

  %p3 = getelementptr i8, ptr %p, i64 3
  %b3 = load i8, ptr %p3, align 1
  %z3 = zext i8 %b3 to i64
  %sh3 = shl i64 %z3, %s

  %or0 = or i64 %acc, %sh0
  %or1 = or i64 %or0, %sh1
  %or2 = or i64 %or1, %sh2
  %r = or i64 %or2, %sh3
  ret i64 %r
}
